config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :service_offerings
  resources :agencies
  
  root 'welcome#index'
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_and_belongs_to_many :service_offerings
  validates :name, presence: true
  validates :city, presence: true
end

app/models/service_offering.rb
class ServiceOffering < ActiveRecord::Base
  has_and_belongs_to_many :agencies
  validates :name, presence: true
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  http_basic_authenticate_with name: "guest", password: "guest", except: [:index, :show]
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:name, :city, { service_offering_ids:[] })
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/service_offerings_controller.rb
class ServiceOfferingsController < ApplicationController
  http_basic_authenticate_with name: "guest", password: "guest", except: [:index, :show]
  before_action :set_service_offering, only: [:show, :edit, :update, :destroy]

  # GET /service_offerings
  # GET /service_offerings.json
  def index
    @service_offerings = ServiceOffering.all
  end

  # GET /service_offerings/1
  # GET /service_offerings/1.json
  def show
  end

  # GET /service_offerings/new
  def new
    @service_offering = ServiceOffering.new
  end

  # GET /service_offerings/1/edit
  def edit
  end

  # POST /service_offerings
  # POST /service_offerings.json
  def create
    @service_offering = ServiceOffering.new(service_offering_params)

    respond_to do |format|
      if @service_offering.save
        format.html { redirect_to @service_offering, notice: 'Service offering was successfully created.' }
        format.json { render :show, status: :created, location: @service_offering }
      else
        format.html { render :new }
        format.json { render json: @service_offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_offerings/1
  # PATCH/PUT /service_offerings/1.json
  def update
    respond_to do |format|
      if @service_offering.update(service_offering_params)
        format.html { redirect_to @service_offering, notice: 'Service offering was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_offering }
      else
        format.html { render :edit }
        format.json { render json: @service_offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_offerings/1
  # DELETE /service_offerings/1.json
  def destroy
    @service_offering.destroy
    respond_to do |format|
      format.html { redirect_to service_offerings_url, notice: 'Service offering was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_offering
      @service_offering = ServiceOffering.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_offering_params
      params.require(:service_offering).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/service_offerings_helper.rb
module ServiceOfferingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/agencies/_form.html.erb
<%= form_for(@agency) do |f| %>
  <% if @agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% @agency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div><br>

  <div> Select Bodyguards Here:
    <%= f.collection_check_boxes(:service_offering_ids, ServiceOffering.all, :id, :name) %>
  </div><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agencies/edit.html.erb
<h1>Edit Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %> | 
<%= link_to 'Bodyguards List', service_offerings_path %>

app/views/agencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Clients and Bodyguards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Bodyguards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agencies.each do |agency| %>
      <tr>
        <td><%= agency.name %></td>
        <td><%= agency.city %></td>
        <td><% agency.service_offerings.each do |so| %>
            <%= so.name %><br>
            <% end %>
            </td>
        </td>
        <td><%= link_to 'Show', agency %></td>
        <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
        <td><%= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Client', new_agency_path %> |
<%= link_to 'Bodyguards List', service_offerings_path %>

app/views/agencies/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Client List', agencies_path %> | 
<%= link_to 'Add New Bodyguard', new_service_offering_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @agency.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @agency.city %>
</p>
<p>
  <strong>Bodyguards</strong><br>
    <% @agency.service_offerings.each do |so| %>
      <%= so.name %><br>
    <% end %>
</p>


<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Habit-Aurora</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/service_offerings/_form.html.erb
<%= form_for(@service_offering) do |f| %>
  <% if @service_offering.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_offering.errors.count, "error") %> prohibited this service_offering from being saved:</h2>

      <ul>
      <% @service_offering.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_offerings/edit.html.erb
<h1>Editing Bodyguard</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_offering %> |
<%= link_to 'Back', service_offerings_path %>

app/views/service_offerings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bodyguards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Clients</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_offerings.each do |service_offering| %>
      <tr>
        <td><%= service_offering.name %></td>
        <td><% service_offering.agencies.each do |agency| %>
            <%= agency.name %><br>
            <% end %></td>
        <td><%= link_to 'Show', service_offering %></td>
        <td><%= link_to 'Edit', edit_service_offering_path(service_offering) %></td>
        <td><%= link_to 'Destroy', service_offering, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Bodyguard', new_service_offering_path %> |
<%= link_to 'Clients List', agencies_path %>

app/views/service_offerings/new.html.erb
<h1>New Bodyguard</h1>

<%= render 'form' %>

<%= link_to 'Back', service_offerings_path %>

app/views/service_offerings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service_offering.name %>
</p>

<%= link_to 'Edit', edit_service_offering_path(@service_offering) %> |
<%= link_to 'Back', service_offerings_path %>

app/views/welcome/index.html.erb
<h1>The Aurora Security Services</h1>
<p></p>
<h2>Welcome!</h2>

<%= link_to 'New Client', new_agency_path %><br>
<p>Click the link above to register a new client. 'User Name' = 'guest', 'Password' = 'guest'</p>